
    ; =============================
    ; DATA SCENES GAME
    ; =============================    
    INCLUDE "SCENES_IM1.INC"            ; Données : modifiables    
    INCLUDE "SCENES.INC"                ; Données : modifiables

    ; =============================
    ; DATA SCENE VIDE
    ; ============================= 
    ;INCLUDE "SCENE_VIDE/DATA.INC"
    INCLUDE "SCENE_TITRE/DATA.INC"
    
