
; -------------------
; PARAMETRES SCENES        ; Identifiants des scènes
; -------------------
ID_SCENE_TITRE             EQU     0

; -------------------
; PARAMETRES TITRE         ; Paramètres de la scène TITRE
; -------------------
TITRE_VRAM                 EQU   SCR_VRAM_BASE
TITRE_TEMPO_3              EQU   150     ; durée 3s : N = 150 / 50
TITRE_PALETTE_SIZE         EQU    11

