
; ----------------------
; PARAMETRES SCENES        ; Identifiants des scènes
; ----------------------
ID_SCENE_TITRE             EQU   0
ID_SCENE_MENU              EQU   0

; ----------------------
; PARAMETRE COLOR GAME
; ----------------------

; ----------------------
; PARAMETRES TITRE         ; Paramètres de la scène TITRE
; ----------------------
TITRE_VRAM                 EQU   SCR_VRAM_BASE
TITRE_TEMPO                EQU   2*50

; ----------------------
; PARAMETRES MENU         ; Paramètres de la scène MENU
; ----------------------

; ----------------------
; PARAMETRES GAMEPLAY     ; Paramètres de la scène GAMEPLAY
; ----------------------

; ----------------------
; PARAMETRES GAMEOVER     ; Paramètres de la scène GAMEOVER
; ----------------------


