
; ----------------------
; PARAMETRES SCENES        ; Identifiants des scènes
; ----------------------

; ----------------------
; PARAMETRE COLOR GAME
; ----------------------

; ----------------------
; PARAMETRES TITRE         ; Paramètres de la scène TITRE
; ----------------------

; ----------------------
; PARAMETRES MENU         ; Paramètres de la scène MENU
; ----------------------

; ----------------------
; PARAMETRES GAMEPLAY     ; Paramètres de la scène GAMEPLAY
; ----------------------

; ----------------------
; PARAMETRES GAMEOVER     ; Paramètres de la scène GAMEOVER
; ----------------------


