
; ----------------------
; PARAMETRES SCENES        ; Identifiants des scènes
; ----------------------
ID_SCENE_VIDE              EQU   0

; ----------------------
; PARAMETRE COLOR GAME
; ----------------------

; ----------------------
; PARAMETRES TITRE         ; Paramètres de la scène TITRE
; ----------------------
TITRE_VRAM                 EQU   SCR_VRAM_BASE
TITRE_PALETTE_SIZE         EQU   2

; ----------------------
; PARAMETRES MENU         ; Paramètres de la scène MENU
; ----------------------

; ----------------------
; PARAMETRES GAMEPLAY     ; Paramètres de la scène GAMEPLAY
; ----------------------

; ----------------------
; PARAMETRES GAMEOVER     ; Paramètres de la scène GAMEOVER
; ----------------------


