
;================================================================
;  INSERTION DES DONNEES SCENE TITRE
;================================================================

    INCLUDE "LETTRES_DATA.INC"

MENU_PAL_DATA
    INCLUDE "MENU_DATA.PAL"

MENU_ZX0_DATA
    INCZX0 "MENU_ZX0_DATA.BIN"

MENU_FLASH_COUNTER_DATA 
    DEFB MENU_FLASH_COUNTER_1

MENU_FLASH_STATE_DATA
    DEFB %10101010

